#include <iostream>
#include <fstream>
#include <iomanip.h>
#include <math.h>
#include <time.h>
#include <map>
#include <TROOT.h>
#include <TSystem.h>
#include <TStyle.h>
#include <TCutG.h>
#include "TChain.h"
#include "TStyle.h"
#include "TCanvas.h"
#include "TEllipse.h"
#include "TString.h"
#include "TGraph.h"
#include "TGraphErrors.h"
#include "TSpectrum.h"
#include "TVirtualFitter.h"
#include "TFitResult.h"
#include "TFitResultPtr.h"
#include "TMatrixDSymfwd.h"
#include "TRandom.h"
#include "TFile.h"
#include "TTree.h"
#include "TH1.h"
#include "TH1D.h"
#include "TH2.h"
#include "TF1.h"
#include "TMath.h"
#include "TPaveText.h"
#include "TSpline.h"
#include "TPad.h"
#include "TAxis.h"
#include "TClass.h"
#include "TMatrixD.h"
#include "TVectorD.h"
#include "string.h"
#include "stdlib.h"
#include "stdio.h"
#include "TLegend.h"
using namespace std;
void Fill1Djoint_DSL()// read data from a txt file and fill a graph and save as a root file
 // multiply two posterior distributions, renormalize and generate a new joint posterior distribution
{//only for 2186*3435 and 4156*5141
	int Eg1,Eg2,Egbinwidth;
	int Taufirst,Taubinwidth;
	int Nbinsx_Tau, Nbinsy_E;
	double Xlow, Xup, Ylow, Yup;
	double input_value[80][80];
	double Sum_input_X[80]={0};
	double Sum_input_Y[80]={0};
	int i,j,k, ;
	double c, d, istep;
	double hight90, lowt, hight, centralt;
	TCanvas *hcanvas[30];
	TCanvas *gcanvas[30];
	TH1D *h1DX [30];
	TGraph *g1DX[30];
	double scale_Y1[6000]={0}, scale_Y2[6000]={0}, scale_Y[6000]={0};
	double scale_X1[6000]={0}, scale_X2[6000]={0};
	char paraprint[300], h_name[300],g_name[300],b_name[300],rootname[300],datname[300], jointname1[300], jointname2[300];
	int ipeak=0;
//	Eg1=4156; Eg2=5141; Xlow=0; Xup=60; Nbinsx_Tau=(Xup-Xlow)*100; Nbinsy_E=50; Ylow=3075.44; Yup=3077.04;
	Eg1=2186; Eg2=3435; Xlow=0; Xup=30; Nbinsx_Tau=(Xup-Xlow)*100; Nbinsy_E=50; Ylow=3075.44; Yup=3077.04;
	sprintf(h_name,"%s%d_times_%d","Likelihood",Eg1,Eg2);
	sprintf(g_name,"%s%d_times_%d","Posterior",Eg1,Eg2);
	sprintf(b_name,"%s%s","D:/X/out/DSL_Final_Tau/",h_name);
	sprintf(rootname,"%s%s",b_name,".root");
	sprintf(datname,"%s%s",b_name,"joint.txt");// Use ANSI txt. Using UTF or Unicode is fucking slow.
	sprintf(jointname1,"%s%0d%s","D:/X/out/DSL_Final_Tau/Likelihood",Eg1,"forjoint.txt"); //generated by Fill1D_DSL.C
	cout<<jointname1<<endl;
	sprintf(jointname2,"%s%0d%s","D:/X/out/DSL_Final_Tau/Likelihood",Eg2,"forjoint.txt"); //generated by Fill1D_DSL.C
	cout<<jointname2<<endl;
	//ofstream outfile(jointname1,ios::out);
	TFile *fout = new TFile(rootname,"RECREATE");

// 	hcanvas[ipeak]=new TCanvas(h_name,h_name,900,600);
// 	hcanvas[ipeak]->cd();
// 	h1DX[ipeak] = new TH1D(h_name,h_name, Nbinsx_Tau, Xlow, Xup);//create and name a histogram
//	TH2F *h2DX = new TH2F("TauEg","TauEg", Nbinsx_Tau, Xlow, Xup, Nbinsy_E, Ylow, Yup);//create and name a histogram
	//TH1F *hChisquare1DY = new TH1F("Eg","Eg", Nbinsy_E, Ylow, Yup);//create and name a histogram
	//TH2F (const char *name, const char *title, Int_t nbinsx, Double_t xlow, Double_t xup, Int_t nbinsy, Double_t ylow, Double_t yup)
	fstream InputByChar_infile1;
	InputByChar_infile1.open(jointname1,ios::in);
	int ibin=0;
	while(!InputByChar_infile1.eof()&&ibin<Nbinsx_Tau)
	{
		InputByChar_infile1>>scale_X1[ibin]>>scale_Y1[ibin]; //read in 6000 pdf points
		//cout<<ibin<<'	'<<scale_X1[ibin]<<'	'<<scale_Y1[ibin]<<endl;
		ibin++;
	}

	fstream InputByChar_infile2;
	InputByChar_infile2.open(jointname2,ios::in);
	ibin=0;
	while(!InputByChar_infile2.eof()&&ibin<Nbinsx_Tau)
	{
		InputByChar_infile2>>scale_X2[ibin]>>scale_Y2[ibin]; //read in 6000 pdf points
		//cout<<ibin<<'	'<<scale_X2[ibin]<<'	'<<scale_Y2[ibin]<<endl;
		ibin++;
	}

	double totalarea=0, ULarea=0;

	for (int ibin = 0; ibin < Nbinsx_Tau; ibin++)
	{
		scale_Y[ibin] = scale_Y1[ibin] * scale_Y2[ibin];
		totalarea+=scale_Y[ibin];
	}
	//cout<<"total=	"<<totalarea<<endl;
	for (int ibin = 0; ibin < Nbinsx_Tau; ibin++)
	{
		scale_Y[ibin] = scale_Y[ibin] / totalarea; // normalize Y
		//cout<<scale_Y[ibin]<<endl;
	}

	for (int ibin = 0; ibin < Nbinsx_Tau; ibin++)
	{
		ULarea += scale_Y[ibin];
		if (ULarea>=1*0.90) break; // Get 90% CL
	}
	hight90=scale_X1[ibin];
	cout<<"90%UL=	"<<hight90<<endl;

	g1DX[ipeak] = new TGraph(Nbinsx_Tau, scale_X1, scale_Y);//TGraph *gr1=new TGraph(n,x,y);
	g1DX[ipeak]->SetTitle(g_name);
	g1DX[ipeak]->SetName(g_name);
	//g1DX[ipeak]->GetXaxis()->SetTitle("Lifetime (fs)");//轴名
	g1DX[ipeak]->GetXaxis()->SetTitle("Parameter #tau (fs)");//轴名
	g1DX[ipeak]->GetYaxis()->SetTitle("Likelihood");//轴名
	g1DX[ipeak]->GetXaxis()->CenterTitle();//居中
	g1DX[ipeak]->GetYaxis()->CenterTitle();//居中
	g1DX[ipeak]->GetXaxis()->SetLabelFont(132);//坐标字体
	g1DX[ipeak]->GetYaxis()->SetLabelFont(132);//坐标字体
	g1DX[ipeak]->GetXaxis()->SetTitleFont(132);//轴名字体
	g1DX[ipeak]->GetYaxis()->SetTitleFont(132);//轴名字体
	//g1DX[ipeak]->GetYaxis()->SetLabelSize(0.05);//坐标字号
	//g1DX[ipeak]->GetYaxis()->SetTitleSize(0.05);//轴名字号
	g1DX[ipeak]->GetXaxis()->SetTitleOffset(1.2);//轴名偏移
	g1DX[ipeak]->GetYaxis()->SetTitleOffset(1.3);//轴名偏移
	//g1DX[ipeak]->SetMarkerStyle(21);
	//g1DX[ipeak]->SetMarkerColor(1);

	gcanvas[ipeak]=new TCanvas(g_name,g_name,900,600);
	gcanvas[ipeak]->cd();
	gPad->SetRightMargin(0.03);

	TSpline3 *s3 = new TSpline3("s3",scale_X1,scale_Y,Nbinsx_Tau);
	s3->SetLineColor(kRed);
	g1DX[ipeak]->SetLineWidth(2);
	g1DX[ipeak]->Draw("AL");
	s3->SetLineWidth(2);
	s3->Draw("l same");

	TPaveText *textpol6 = new TPaveText(0.50,0.75,0.97,0.90,"brNDC");//left, down, right, up
	textpol6->SetBorderSize(1);
	textpol6->SetFillColor(0);
	textpol6->SetTextAlign(12);//align = 10*HorizontalAlign + VerticalAlign, 12 means水平左对齐、垂直居中对齐
	textpol6->SetTextFont(132);//font = 10 * fontID + precision, 12+2,12 means Symbol; 13+2, 13 means News Times Roman
	sprintf(paraprint,"90%% UL=%.1f%s",hight90," fs"); // modify
	textpol6->AddText(paraprint);
	textpol6->Draw();

	gcanvas[ipeak]->Update();
	//h2DX->Draw("colz");
	g1DX[ipeak]->Write();
	fout->Write();
	//fout->Close();
}//Fill2D main